In [23]:
import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_csv("assignment3.csv")
data

      Age  Income Student Creditrating Buyscomputer
0   Youth    High      No         Fair           No
1   Youth    High      No    Excellent           No
2  Middle    High      No         Fair          Yes
3  Senior  Medium      No         Fair          Yes
4  Senior     Low     Yes         Fair          Yes
5  Middle     Low     Yes    Excellent           No
6  Senior     Low     Yes    Excellent          Yes
7   Youth  Medium      No         Fair          Yes

In [24]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]
y

0     No
1     No
2    Yes
3    Yes
4    Yes
5     No
6    Yes
7    Yes
Name: Buyscomputer, dtype: object

In [25]:
x['Age']=x['Age'].map({'Youth':1,'Middle':2,'Senior':3})
x['Income']=x['Income'].map({'High':1, 'Medium':2, 'Low':3})
x['Student']=x['Student'].map({'No':0, 'Yes':1})
x['Creditrating']=x['Creditrating'].map({'Fair':1, 'Excellent':2})
x

C:\Users\student\AppData\Local\Temp\ipykernel_1828\350998991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Age']=x['Age'].map({'Youth':1,'Middle':2,'Senior':3})
C:\Users\student\AppData\Local\Temp\ipykernel_1828\350998991.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Income']=x['Income'].map({'High':1, 'Medium':2, 'Low':3})
C:\Users\student\AppData\Local\Temp\ipykernel_1828\350998991.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Student']=x['Student'].map({'No':0, 'Yes':1})
C:\Users\student\AppData\Local\Temp\ipykernel_1828\350998991.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Creditrating']=x['Creditrating'].map({'Fair':1, 'Excellent':2})

   Age  Income  Student  Creditrating
0    1       1        0             1
1    1       1        0             2
2    2       1        0             1
3    3       2        0             1
4    3       3        1             1
5    2       3        1             2
6    3       3        1             2
7    1       2        0             1

In [28]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x,y)
print(nb.predict([[3,3,1,1]]))

['Yes']

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(